    apiVersion: argoproj.io/v1alpha1
    kind: ApplicationSet
    metadata:
      name: cloudraider
      namespace: argocd
    spec:
      generators:
      - matrix:
          generators:
          - pullRequest:
              github:
                # The GitHub organization or user.
                owner: CloudknightOps
                # The Github repository
                repo: CICD-with-Github-action-and-Argocd 
                labels:
                - preview
              requeueAfterSeconds: 90
          - list:
              elements:
              - url: https://github.com/CloudknightOps/CICD-with-Github-action-and-Argocd
                path: deploy 
      - matrix:
          generators:
          - pullRequest:
              github:
                # The GitHub organization or user.
                owner: CloudknightOps
                # The Github repository
                repo:  Dynamic-PR-test
                labels:
                - preview
              requeueAfterSeconds: 90
          - list:
              elements:
              - url: https://github.com/CloudknightOps/Dynamic-PR-test
                path: helm/webapp
      - matrix:
          generators:
          - pullRequest:
              github:
                # The GitHub organization or user.
                owner: CloudknightOps
                # The Github repository
                repo:  Pull-request-test
                labels:
                - preview
              requeueAfterSeconds: 90
          - list:
              elements:
              - url: https://github.com/CloudknightOps/Pull-request-test
                path: deploy
                
      template:
          metadata:
            name: 'cloudraider-{{branch}}-{{number}}'
            namespace: argocd 
          spec:
            source:
              repoURL: '{{ url }}'
              targetRevision: '{{head_sha}}'
              path: '{{ path }}'
            project: "default"
            destination:
              server: https://kubernetes.default.svc
              namespace: cloud-{{branch}}-{{number}}
            syncPolicy:
              syncOptions:
                - CreateNamespace=true